# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:               's3a'
tagline:             'testing times'
description:         'The musing of a parent, photographer and software tester'
url:                 'https://s3a.uk'
baseurl:          /

author:
  name:           'Jonathan'
  url:            https://twitter.com/whatie

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
